In [1]:
import numpy as np


a = np.matrix([[2, -3, 1], [0, 1, 2], [2, 0, -1]])
b = np.matrix([[4], [5], [8]])

print(a)
print(b)


### Elementary operations

E = a.copy()




[[ 2 -3  1]
 [ 0  1  2]
 [ 2  0 -1]]
[[4]
 [5]
 [8]]
[[ 2 -3  1]
 [ 0  1  2]
 [ 2  0 -1]]
