## Problem 10

In [189]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [192]:
def hilbert(n):
    x = np.arange(1, n+1) + np.arange(0, n)[:, np.newaxis]
    return 1.0/x

def swapRow(A,r1,r2):
    # put row r2 in r1 spot
    print('Swapping rows')
    A_new = np.copy(A)
    for i in range(len(A_new)):
        temp_var = A_new[r1][i]
        A_new[r1][i] = A_new[r2][i]
        A_new[r2][i] = temp_var

    return A_new





def gaussianElimination(A,b): #nxn matrices only
    A_temp = np.copy(A)
    A_inv = np.identity(len(A))
    b_temp = np.copy(b)

    #making zeros below diagnal
    for c in range(len(A)): #columns
        if(A_temp[c][c] == 0): # zero along the diagnal
                for i in range(c,len(A[0])):
                    if(A_temp[i][c] != 0):
                        A_temp = np.copy(swapRow(A_temp,c,i))
                        A_inv = np.copy(swapRow(A_inv,c,i))
        for r in range(c+1,len(A[0])): #rows
            #print('r: '+str(r)+'        c: '+str(c)+'        d: '+str(c)+','+str(c))
            if(A_temp[r][c] != 0):
                temp = A_temp[r][c]*(-1.0)/A_temp[c][c] # value @ index trying to get to zero *(-1)/value along diagnal
                b_temp[r][0] = b_temp[r][0] + temp*b_temp[c][0]
                for i in range(c,len(A)):
                    A_temp[r][i] = A_temp[r][i] + temp*A_temp[c][i]
                for i in range(len(A)):
                    A_inv[r][i] = A_inv[r][i] + temp*A_inv[c][i]

    
    #print('Above time')
    #print()
    #making zeros above diagnal
    for c in range(1,len(A)): #columns
        if(A_temp[c][c] == 0): # zero along the diagnal
                for i in range(c,len(A[0])):
                    if(A_temp[i][c] != 0):
                        A_temp = np.copy(swapRow(A_temp,c,i))
                        A_inv = np.copy(swapRow(A_inv,c,i))
        for r in reversed(range(c)): #rows
            #print('r: '+str(r)+'        c: '+str(c)+'        d: '+str(c)+','+str(c))
            if(A_temp[r][c] != 0):
                temp = A_temp[r][c]*(-1.0)/A_temp[c][c] # value @ index trying to get to zero *(-1)/value along diagnal
                b_temp[r][0] = b_temp[r][0] + temp*b_temp[c][0]
                for i in range(c,len(A)):
                    A_temp[r][i] = A_temp[r][i] + temp*A_temp[c][i]
                for i in range(len(A)):
                    A_inv[r][i] = A_inv[r][i] + temp*A_inv[c][i]


    #print('A: '+str(A_temp))
    #print('A_inv: '+str(A_inv))
    #print('b: '+str(b_temp))

    #print('Make diagnals 1')
    #print()
    #making diagnals 1
    for i in range(len(A)):
        temp = 1.0/A_temp[i][i]
        b_temp[i][0] *= temp
        A_temp[i][i] *= temp
        for j in range(len(A)):
            A_inv[i][j] *= temp





    #print('The solution is correct if: '+str(np.matmul(A_inv,b) == b_temp))
    #print('AA^-1 = I -->'+str(np.matmul(A,A_inv) == np.identity(len(A))))

    print('The solution is correct if A^-1b == b_')


    return A_inv,b_temp,A_temp




In [193]:
m = 4
a = hilbert(m)
#b = np.array([[0.564348], [0.93798], [0.707275],[0.0248771]])
b = np.array([[1], [2], [3],[4]])

t = gaussianElimination(a,b)
print('My programs inverse to problem #9 was:')
print(t[0])
print('The solution to the system of linear equations in problem #9 is:')
print(t[1])
print()



AA^-1 = I -->[[False  True False False]
 [False False False False]
 [False False False False]
 [False False False False]]
My programs inverse to problem #9 was:
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
The solution to the system of linear equations in problem #9 is:
[[ -284]
 [ 3360]
 [-8280]
 [ 5599]]



In [186]:
# 10x10 matrix
m = 10
a = hilbert(m)
b = np.array([[1]]*m)
for i in range(len(b)):
    b[i][0]=i+1


t = gaussianElimination(a,b)
print('If the following is an identity matrix then the inverse was found correctly:')
print(np.matmul(t[2],t[0]))

If the following is an identity matrix then the inverse was found correctly:
[[ 9.99963466e+01 -4.94968266e+03  7.91932148e+04 -6.00538137e+05
   2.52222426e+06 -6.30548555e+06  9.60826178e+06 -8.75030521e+06
   4.37511957e+06 -9.23630235e+05]
 [-4.94968280e+03  3.26672459e+05 -5.88001130e+06  4.75621538e+07
  -2.08082251e+08  5.35063976e+08 -8.32315574e+08  7.70028551e+08
  -3.89824797e+08  8.31272187e+07]
 [ 7.91932198e+04 -5.88001146e+06  1.12894943e+08 -9.51235774e+08
   4.28052900e+09 -1.12363184e+10  1.77560632e+10 -1.66326446e+10
   8.50529589e+09 -1.82880726e+09]
 [-6.00538194e+05  4.75621563e+07 -9.51235795e+08  8.24399246e+09
  -3.78706474e+10  1.00987962e+11 -1.61580155e+11  1.52886126e+11
  -7.88316955e+10  1.70689305e+10]
 [ 2.52222457e+06 -2.08082267e+08  4.28052917e+09 -3.78706481e+10
   1.76729135e+11 -4.77167406e+11  7.71177917e+11 -7.35765267e+11
   3.82031324e+11 -8.32112857e+10]
 [-6.30548650e+06  5.35064026e+08 -1.12363190e+10  1.00987966e+11
  -4.77167413e+11  1.3

In [187]:
# 100x100 matrix
m = 100
a = hilbert(m)
b = np.array([[1]]*m)
for i in range(len(b)):
    b[i][0]=i+1


t = gaussianElimination(a,b)
print('If the following is an identity matrix then the inverse was found correctly:')
print(np.matmul(t[2],t[0]))

If the following is an identity matrix then the inverse was found correctly:
[[ 1.62033993e+02 -1.30494155e+04  3.39760303e+05 ...  6.14340221e+08
  -3.08299851e+08 -2.49853661e+08]
 [-1.32398727e+04  1.44055489e+06 -4.27970508e+07 ... -1.13155238e+11
   6.33852485e+10  4.15408004e+10]
 [ 3.55371413e+05 -4.40843750e+07  1.41746233e+09 ...  4.97914340e+12
  -3.13614934e+12 -1.64488457e+12]
 ...
 [-3.84863803e+08  1.08391616e+11 -6.17441003e+12 ...  3.83516450e+17
  -2.47754423e+17  1.83774058e+16]
 [ 6.54909412e+08 -1.49019397e+11  7.58032023e+12 ... -3.31222611e+17
   3.03310826e+17 -9.94954939e+16]
 [-1.34480376e+08  3.11948117e+10 -1.59530647e+12 ...  5.57843597e+16
  -8.96065446e+16  5.83555373e+16]]


In [188]:
# 200x200 matrix
m = 20
a = hilbert(m)
b = np.array([[1]]*m)
for i in range(len(b)):
    b[i][0]=i+1


t = gaussianElimination(a,b)
print('If the following is an identity matrix then the inverse was found correctly:')
print(np.matmul(t[2],t[0]))

If the following is an identity matrix then the inverse was found correctly:
[[ 1.14433019e+02 -5.69344557e+03  6.19960855e+04  2.70706569e+05
  -8.93238975e+06  6.51095110e+07 -2.24514188e+08  3.52538616e+08
   7.12267519e+06 -8.33786976e+08  8.80084502e+08  4.06411236e+08
  -1.25447686e+09  8.28123788e+08 -5.45951746e+08 -2.01230645e+07
   1.91192220e+09 -2.95019087e+09  1.78032758e+09 -3.93991180e+08]
 [-5.74397759e+03  2.77059873e+05  1.36930008e+06 -1.41216400e+08
   1.89358432e+09 -1.16591310e+10  3.77585003e+10 -5.81848597e+10
   2.14051223e+09  1.26006344e+11 -1.32925962e+11 -6.99920421e+10
   2.12570260e+11 -1.51890081e+11  9.04794203e+10  1.78523267e+10
  -3.05987077e+11  4.51493559e+11 -2.68410626e+11  5.89948526e+10]
 [ 6.57567399e+04  1.09014109e+06 -3.07584481e+08  7.98195692e+09
  -8.68169247e+10  4.94090267e+11 -1.54651029e+12  2.37573099e+12
  -2.59238209e+11 -4.64116918e+12  4.93114055e+12  2.98258714e+12
  -8.94133968e+12  6.81591828e+12 -3.65954002e+12 -1.31540562e+

From what I can tell from the output above that as I increased the size of the Hilbert matrix the accuracy of my inverse matrix got worse and worse most likely due how small the values of this matrix get when there are large lengthed matrices invovled.